{
 "title": "PostgreSQL Overview",
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "pg_stat_activity_count", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pg_database_size_bytes", "legendFormat": "{{datname}}" }
   ]
  },
  {
   "title": "Transactions Commits",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit[2m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions Rollbacks",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback[2m])",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}